server {
    listen 80;
    server_name [域名];

    location / {
        proxy_pass http://ticket:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name [域名];

    ssl_certificate /etc/letsencrypt/live/[域名]/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/[域名]/privkey.pem;

    location / {
        proxy_pass http://ticket:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
